export const ADD_TO_CART='ADD_TO_CART';
export const TOGGLE_REMOVE_FROM_CART='TOGGLE_REMOVE_FROM_CART';
export const CHANGE_QUANTITY='CHANGE_QUANTITY';
export const RESET_CART_REDUCER='RESET_CART_REDUCER';
export const CLEAN_REMOVED_ITEMS='CLEAN_REMOVED_ITEMS';
export const ADD_ADDRESS='ADD_ADDRESS';
export const TOGGLE_ADDRESS_SELECTION_IN_ORDER='TOGGLE_ADDRESS_SELECTION_IN_ORDER';
