export const CART_FINALIZE_ORDER_MODAL = 'CART_FINALIZE_ORDER_MODAL';
export const MODAL_HIDDEN_CLASS = 'modal_hidden';
export const MODAL_VISIBLE_CLASS = 'modal_visible';
export const SETTINGS_ADDRESS_REMOVAL_MODAL = 'SETTINGS_ADDRESS_REMOVAL_MODAL';